{
  "language": "generic",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": true,
  "services": [
    "docker"
  ],
  "before_install": [
    "docker build -t jordan/docker-react -f Dockerfile.dev ."
  ],
  "script": [
    "docker run -e CI=true jordan/docker-react npm run test"
  ]
}