sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jordan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jordan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-620524101278'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY